Alexmnet news
reskillamericans/website pull request #108
Opened 2022-01-24 22:00 UTC by AlexMNet

2022-01-24 22:30 UTC, mckoss requested changes
A few changes to make.

2022-01-24 22:30 UTC, mckoss commented on themes/ra-theme/assets/css/header.scss
> +    background-color: 'transparent';
no quotes

2022-01-24 22:30 UTC, mckoss commented on themes/ra-theme/assets/css/header.scss
> +        background-color: 'hsla(0, 0%, 100%, 0.5)';
no quotes

2022-01-24 22:30 UTC, mckoss commented on themes/ra-theme/assets/css/summary.scss
> +  max-width: 990px;
Please add as a breakpoint in the breakpoint.scss file.

2022-01-24 23:42 UTC, AlexMNet commented
- Removed the quotes from the header sass file
- Removed center alignment on images
- Added max-summary-width of 990px to breakpoints

2022-01-25 18:36 UTC, mckoss approved these changes
Looks great, Alex.  "LGTM"

2022-01-25 18:36 UTC, merged